api/urls.py
from django.urls import path
from .views import employee as emp, main, supervisor as spv

app_name = 'api'

""" main Urls """
urlpatterns = [
    path('', main.documentation, name='main'),
    path('login', main.UserLogin.as_view(), name='login-api'),
    path('user', main.UserAuthenticated.as_view(), name='user-auth'),
    path('logout', main.UserLogout.as_view(), name='logout'),
]

""" this is the part for the employee side """
urlpatterns += [
    path('assignment-control', emp.assignment_control, name='emp-ass'),
    path('assignment-control/img/<slug:uid>', emp.img_upload, name='emp-ass'),
    path('assignment-control/list/<slug:uid>', emp.assignment_list_detail, name='emp-ass'),
    path('qr-validating/<slug:uid>', emp.qr_validating, name='emp-det'),
]

""" this is the part of the supervisor """
urlpatterns += [
    path('supervisor', spv.AssignmentListOnMine.as_view(), name='spv'),
    path('supervisor/all-employee', spv.all_employee, name='all_emp'),
    path('supervisor/work-place', spv.WorkPlaceEndPoint.as_view(), name='work-place'),
    path('supervisor/links', spv.CreateInvitationLinkAPI.as_view(), name='links'),
]

dashboard/urls.py
from django.urls import path
from .views import main, employee as emp, supervisor as sv

app_name = 'dash'

urlpatterns = [
    path('', main.level_check, name='main'),
    path('is-invited-you/<slug:link>', main.invitation_registering, name='manual-registering'),
    path('Registered', main.LandingPage.as_view(), name='registered'),
    path('delete', sv.delete_all_assignment_control, name='delete-all'),
]

urlpatterns += [
    path('Supervisor', sv.DashboardView.as_view(), name='home'),
    path('Supervisor/show_qr/<qr_code>', sv.ShowQRCode.as_view(), name='qr-code'),
    path('Supervisor/LokasiKerja', sv.CreateWorkPlace.as_view(), name='create-work'),
    path('Supervisor/BerikanPekerjaan', sv.create_job, name='create-job'),
    path('generate_link', sv.CreateInvitationLink.as_view(), name='links'),
]

urlpatterns += [
    path('Employee', emp.EmployeeDashboard.as_view(), name='emp'),
    path('Employee/<int:pk>/', emp.qr_validating, name='emp-qr'),
    path('Employee/<int:pk>/list', emp.MyJobDetail.as_view(), name='emp-list'),
    path('Employee/<int:pk>/done', emp.set_list_to_done, name='emp-done'),
    path('Employee/<int:pk>', emp.UpdateJob.as_view(), name='emp-do'),
]

house/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [path('', include('dashboard.urls', namespace='dash'))]

dashboard/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm


class SetOnProgress(forms.ModelForm):
    class Meta:
        model = AssignmentControl
        fields = ['img_before']


class MarkAsDone(forms.ModelForm):
    class Meta:
        model = AssignmentControl
        fields = ['img_after']


class CreateWorkPlaceForm(forms.ModelForm):
    class Meta:
        model = WorkPlace
        fields = ['buildings', 'tower_name', 'ground_name', 'job_area']


class CreateEmployeeJob(forms.ModelForm):
    class Meta:
        model = AssignmentControl
        fields = ['assignment', 'estimated_time', 'for_day']

        widgets = {
            'for_day': forms.DateInput(format='%d/%m/%Y', attrs={'type': 'date'})
        }


class CreateMainUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class UserExtendedForm(forms.ModelForm):
    class Meta:
        model = EmployeeManagement
        fields = ['nik', 'profile_img', 'phone_number', 'gender']


class CreateLinkForms(forms.ModelForm):
    class Meta:
        model = InvitationLink
        fields = '__all__'

dashboard/views/employee.py
from .main import *


class EmployeeDashboard(ListView):
    model = AssignmentControl
    template_name = 'd/em.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return AssignmentControl.objects.filter(
            worker=self.request.user
        )

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        emp = self.request.user.emp_user.is_employee
        spv = self.request.user.emp_user.is_supervisor
        if emp and not spv:
            return super(EmployeeDashboard, self).dispatch(request, *args, **kwargs)
        elif emp and spv:
            return redirect('dash:home')
        logout(self.request)
        return redirect('/accounts/login/')


class UpdateJob(UpdateView):
    model = AssignmentControl
    query_pk_and_slug = True
    pk_url_kwarg = 'pk'
    template_name = 'd/form.html'

    def get_success_url(self):
        return reverse('dash:emp-list', args=[self.kwargs['pk']])

    def get_form_class(self):
        get_assignment = get_object_or_404(AssignmentControl, pk=self.kwargs['pk'])
        if get_assignment.on_progress:
            self.form_class = MarkAsDone
        else:
            self.form_class = SetOnProgress
        return self.form_class

    def form_valid(self, form):
        get_assignment = get_object_or_404(AssignmentControl, pk=self.kwargs['pk'])
        file_before = self.request.FILES.get('img_before')
        file_after = self.request.FILES.get('img_after')
        if not file_after and not file_before:
            return HttpResponseRedirect(reverse('dash:emp-do', args=[self.kwargs['pk']]))
        elif not file_after or not file_before:
            if get_assignment.on_progress:
                form.instance.is_done = True
                form.instance.on_progress = False
                form.instance.end_time = timezone.now()
            else:
                form.instance.on_progress = True
                form.instance.start_time = timezone.now()
        return super(UpdateJob, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        get_assignment = get_object_or_404(AssignmentControl, pk=self.kwargs['pk'])
        if get_assignment.is_done:
            return HttpResponseRedirect(reverse('dash:emp'))
        elif not get_assignment.access_permission:
            return HttpResponseRedirect(reverse('dash:emp-qr', args=[self.kwargs['pk']]))
        return super(UpdateJob, self).dispatch(request, *args, **kwargs)


def do_job(request, pk):
    get_assignment = get_object_or_404(AssignmentControl, pk=pk)
    if request.method == 'POST':
        if get_assignment.on_progress:
            get_assignment.end_time = timezone.now()
            get_assignment.is_done = True   
            get_assignment.on_progress = False
            get_assignment.save()
        elif get_assignment.is_done:
            pass
        else:
            get_assignment.start_time = timezone.now()
            get_assignment.on_progress = True
            get_assignment.save()
    return redirect('dash:emp')


def qr_validating(request, pk):
    context = {}
    get_assignment = get_object_or_404(AssignmentControl, pk=pk)
    if get_assignment.is_done:
        return redirect('dash:emp')
    work = get_assignment.assignment.qr_code
    if request.method == 'POST':
        qr_code = request.POST.get('qr_c')
        if qr_code is not None and qr_code == work:
            get_assignment.access_permission = True
            get_assignment.save()
            return HttpResponseRedirect(reverse('dash:emp-do', args=[pk]))
    context['this_ass'] = work
    return render(request, 'd/read.html', context)


class MyJobDetail(DetailView):
    model = AssignmentControl
    template_name = 'd/job_detail.html'
    query_pk_and_slug = True
    pk_url_kwarg = 'pk'
    context_object_name = 'ass_con'

    def get_context_data(self, **kwargs):
        context = super(MyJobDetail, self).get_context_data(**kwargs)
        get_ass = get_object_or_404(AssignmentControl, pk=self.kwargs['pk'])
        ass_list = AssignmentListControl.objects.filter(assignment_control=get_ass)

        context['ass_list'] = ass_list
        return context

    def dispatch(self, request, *args, **kwargs):
        get_assignment = get_object_or_404(AssignmentControl, pk=self.kwargs['pk'])
        emp = self.request.user.emp_user.is_employee
        spv = self.request.user.emp_user.is_supervisor
        if get_assignment.is_done:
            return redirect('dash:emp')
        elif not get_assignment.access_permission:
            return HttpResponseRedirect(reverse('dash:emp-qr', args=[self.kwargs['pk']]))
        if emp and spv:
            return redirect('dash:home')
        elif emp and not spv:
            return super(MyJobDetail, self).dispatch(request, *args, **kwargs)


def set_list_to_done(request, pk):
    get_list = request.POST.getlist('control')
    print(get_list)
    if get_list:
        for element in get_list:
            control = get_object_or_404(AssignmentListControl, pk=int(element))
            control.is_done = True
            print(control)
            control.save()

    return HttpResponseRedirect(reverse('dash:emp-do', args=[pk]))

dashboard/views/supervisor.py
from .main import *


class CreateWorkPlace(CreateView):
    model = WorkPlace
    template_name = 'd/form.html'
    form_class = CreateWorkPlaceForm

    def get_success_url(self):
        return reverse('dash:home')

    def form_valid(self, form):
        wp_data = WorkPlace.objects.all()
        code_data = [x.qr_code for x in wp_data]
        code = generate_code()
        while True:
            if code in code_data:
                code = generate_code()
            else:
                break

        form.instance.qr_code = code
        return super(CreateWorkPlace, self).form_valid(form)

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(CreateWorkPlace, self).dispatch(request, *args, **kwargs)


class DashboardView(ListView):
    template_name = 'd/home.html'
    model = AssignmentControl
    context_object_name = 'jobs'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        employee = self.request.user.emp_user.is_employee
        supervisor = self.request.user.emp_user.is_supervisor
        if employee and supervisor:
            stat = 'supervisor'
        else:
            stat = 'employee'

        qr = WorkPlace.objects.all()

        inv = InvitationLink.objects.all()

        context['qr'] = qr
        context['stat'] = stat
        context['link'] = inv
        return context

    def get_queryset(self):
        return AssignmentControl.objects.filter(given_by=self.request.user)

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        spv = self.request.user.emp_user.is_supervisor
        emp = self.request.user.emp_user.is_employee
        if spv and emp:
            return super(DashboardView, self).dispatch(request, *args, **kwargs)
        elif emp and not spv:
            return redirect('dash:emp')
        logout(self.request)
        return redirect('/accounts/login/')


@login_required(login_url='/accounts/login/')
def create_job(request):
    emp = EmployeeManagement.objects.filter(is_employee=True, is_supervisor=False)
    form = CreateEmployeeJob()

    if request.method == 'POST':
        form = CreateEmployeeJob(request.POST or None, request.FILES or None)
        emp_list = request.POST.getlist('emp')
        print(emp_list)
        if form.is_valid():
            est_time = form.cleaned_data['estimated_time']
            assignment = form.cleaned_data['assignment']
            day = form.cleaned_data['for_day']
            ass_data = AssignmentControl.objects.all()
            code_data = [x.uid for x in ass_data]
            code = assignment_code()
            while True:
                if code in code_data:
                    code = assignment_code()
                else:
                    break

            for employee in emp_list:
                get_worker = get_object_or_404(EmployeeManagement, pk=int(employee))
                job = AssignmentControl.objects.create(
                    assignment=assignment, estimated_time=est_time,
                    worker=get_worker.user, for_day=day,
                    given_by=request.user, uid=code
                )
                job.save()
                get_list = AssignmentList.objects.filter(for_job=assignment)
                for ass_list in get_list:
                    list_control = AssignmentListControl.objects.create(
                        assignment_control=job,
                        assignment_list=ass_list
                    )
                    list_control.save()
            return redirect('dash:home')
    context = {
        'employee': emp,
        'form': form,
    }
    return render(request, 'd/form.html', context)


def delete_all_assignment_control(request):
    dataset = AssignmentControl.objects.all()
    dataset_list = AssignmentListControl.objects.all()
    if request.method == 'POST':
        for data in dataset:
            data.delete()
        for lst in dataset_list:
            lst.delete()
    return redirect('dash:home')


class CreateInvitationLink(CreateView):
    model = InvitationLink
    template_name = 'd/reg.html'
    form_class = CreateLinkForms

    def get_success_url(self):
        return reverse('dash:emp')

    def form_valid(self, form):
        user = self.request.user
        valid_until = timezone.now() + datetime.timedelta(1)
        inv_data = InvitationLink.objects.all()
        code_data = [x.link for x in inv_data]
        code = invitation_code()
        while True:
            if code in code_data:
                code = invitation_code()
            else:
                break

        form.instance.link = code
        form.instance.spv = user
        form.instance.valid_until = valid_until
        return super(CreateInvitationLink, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateInvitationLink, self).get_context_data(**kwargs)
        opened = True
        context['open'] = opened
        return context

    @method_decorator(login_required(login_url='accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(CreateInvitationLink, self).dispatch(request, *args, **kwargs)


class ShowQRCode(DetailView):
    model = WorkPlace
    slug_field = 'qr_code'
    slug_url_kwarg = 'qr_code'
    query_pk_and_slug = True
    template_name = 'd/qr.html'
    context_object_name = 'code'

dashboard/templates/d/do.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>do job oke</p>

</body>
</html>

dashboard/templates/d/em.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>di halama ini menjelaskan bahwa setiap user setelah login aka di check</p>
{{ user }} <br>
<div class="">
    {% for job in jobs %}
    <a href="{% url 'dash:emp-qr' job.pk %}">{{ job }}</a> <br>
    {% endfor %}
</div>
</body>
</html>

dashboard/templates/d/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>di halama ini menjelaskan bahwa setiap user setelah login aka di check</p>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if employee %}
        {% for emp in employee %}
            <input type="checkbox" id="emp" name="emp" value="{{emp.id}}"> {{ emp }} <br>
        {% endfor %}
    {% endif %}
    <br>
    <button>Save</button>
</form>
</body>
</html>

dashboard/templates/d/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>di halama ini menjelaskan bahwa setiap user setelah login aka di check</p>
{{ user }} <br>
{{ stat }} <br>
<!--<a href="{% url 'dash:create-work' %}">Klik disini buat lokasi kerja</a> <br>-->
<a href="{% url 'dash:create-job' %}">Klik disini berikan pekerjaan</a>
<br>
{% for job in jobs %}
    {{ job }} <br>
{% endfor %}
<br> <br>
<form action="{% url 'dash:delete-all' %}" method="post">
    {% csrf_token %}
    <button>delete</button>
</form>

<br> <br>
{% for inv in link %}
    {{ inv }} | {{ inv.status_print }} <br>
{% endfor %}
<br>
<br>
<form action="{% url 'dash:links' %}" method="post">
    {% csrf_token %}
    <button> Get new Link</button>
</form>
<br>
<h4>see qr code</h4>
<p>
    {% for code in qr %}
    <a href="{% url 'dash:qr-code' code.qr_code %}">{{ code.qr_code }}</a> <br>
    {% endfor %}
</p>
</body>
</html>

dashboard/templates/d/job_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail job for me</title>
</head>
<body>
<form action="{% url 'dash:emp-done'  ass_con.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for list in ass_list %}
    <input type="checkbox" name="control" id="control" value="{{ list.pk }}"> {{list}} <br>
    {% endfor %}
    <br>
    <button>save</button>
</form>

</body>
</html>

dashboard/templates/d/qr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="{{ code.qr_img.url }}" alt="qr code img">
</body>
</html>

dashboard/templates/d/read.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>masukan kode dari qr contoh doang nanti yang akan dikirm adalah hasil dekrispi dari qr code yg berbentuk gambar </p>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="qr_c">
    <button>save</button>
</form>
<br>
{{ this_ass }} <br>
{{ der }}
</body>
</html>

dashboard/templates/d/reg.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load l10n %}
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/register.css' %}">
        <title>Register Account</title>
    </head>
    <body>
        <div class="container my-auto">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="login-form">
                        {% if open %}
                        <form enctype="multipart/form-data" method="POST">
                            {% load crispy_forms_tags %}
                            {% csrf_token %}
                            {{ form | crispy }}
                            {{ e_form | crispy }}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                        {% else %}
                            {% if messages %}
                                {% for msg in messages %}
                                <h1 class="text-center">{{ msg }}</h1>
                                {% endfor %}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script>
            // $(".login-action").click(function(){
            //   alert("clicked.");
            // });

        </script>
    </body>
</html>